### PR TITLE
fix(module): only parse global components

### PR DESCRIPTION
**Pull request by farnabaz**
resolves nuxtlabs/nuxt-component-meta#50

### CODE REVIEW

**Comment by farnabaz** [comment]
I don't understand why slots are not detected when I filter global components 

```
component.fullPath /Users/far/projects/nuxt/nuxt-component-meta/test/fixtures/basic/components/global/TestContent.vue 
slots: [
  {
    name: 'title',
    type: '{}',
    rawType: undefined,
    description: '',
    schema: { kind: 'object', type: '{}', schema: {} }
  },
  {
    name: 'default',
    type: '{}',
    rawType: undefined,
    description: '',
    schema: { kind: 'object', type: '{}', schema: {} }
  }
] 
<template>
  <div>
    <h1><slot name="title" /></h1>
    <slot  />
  </div>
</template>

<script setup>defineProps()</script>
```
# filtered

```
component.fullPath /Users/far/projects/nuxt/nuxt-component-meta/test/fixtures/basic/components/global/TestContent.vue 
slots: [] 

<template>
  <div>
    <h1><slot name="title" /></h1>
    <slot  />
  </div>
</template>

<script setup>defineProps()</script>
```

@Tahul do you have an idea about it?

**Review by Atinux — APPROVED** [review]

**Comment by Atinux** [comment]
We need to find a solution for this

**Comment by Tahul** [comment]
Looking into it :)

**Comment by stafyniaksacha** [comment]
I think this should be configurable

**Comment by Tahul** [comment]
Issue is fixed and tests are passing; merging this.

I added the feature behind `globalsOnly` option that can be enabled from the module config.

**Pull request merged**
