### PR TITLE
feat(unplugin): move parsing steps to unplugin

### PR DESCRIPTION
**Pull request by Tahul**
This PR moves parsing steps inside an Unplugin, instead of the root scope of the Nuxt module.

This allows supporting HMR.

The PR in its current state supports reparsing components on-save, I get the output file (`.nuxt/component-meta.mjs`) to refresh on each changes, with proper updates.

It needs fixes on HMR before merging, but I can already see few issues:

- We can't pass a string to `createComponentMetaCheckerByJsonConfig`

That would be very helpful to support generating metas from transformed components and not their only the content of the file. That can be useful if the project contains any plugin that may alter the content of <template> or <script>.

I could then run that parsing step from inside the `transform` hook of the Unplugin, and updating my context from that result based on transformed component content.

cc @johnsoncodehk :)

- Is there a smoother way of communicating dynamic data between Nitro <=> Vite than writing a file?

---

Will resolve: https://github.com/nuxtlabs/nuxt-component-meta/issues/42, https://github.com/nuxtlabs/nuxt-component-meta/issues/33

Will help on: https://github.com/nuxt-themes/elements/issues/93

### CODE REVIEW

**Comment by Tahul** [comment]
putting this back as draft ; virtual modules breaking build ; not ready yet

**Comment by Tahul** [comment]
I changed the implementation for it to work with both build and HMR; should be ready for review @farnabaz

**Comment by Tahul** [comment]
tests passes :)

**Comment by farnabaz** [comment]
"mode": "all",
    "global": true,
    "prefetch": false,
    "preload": false,
    "filePath": "/components/global/TestGlobalComponent.vue",
    "pascalName": "TestGlobalComponent",
    "kebabName": "test-global-component",
    "chunkName": "components/test-global-component",
    "shortPath": "components/global/TestGlobalComponent.vue",
    "export": "default",
    "fullPath": "/Users/far/projects/nuxt/nuxt-component-meta/playground/components/global/TestGlobalComponent.vue",

**Comment by farnabaz** [comment]
I think we can remove some fields from generated meta, fields likes `fullPath`, `shortPath`, `export`, `fileName`, `chunkName`, ...
I don't see these fields as useful fields in runtime and removing them will reduce template size also

WDYT @Tahul ?

**Comment by Atinux** [comment]
Agree that some could be trimmed to the essentials to reduce the generate code.

Another note is that the generated code should never be included in the end-user bundle but only when:
1. Calling the API endpoint
2. Calling the composables (that should call the API endpoint in production with no HMR)
3.

**Comment by stafyniaksacha** [comment]
> Another note is that the generated code should never be included in the end-user bundle but only when:
> 
> 1. Calling the API endpoint
> 2. Calling the composables (that should call the API endpoint in production with no HMR)

We may want to expose this to the end-user bundle as an opt-in option, so we can use the unplugin as standalone (e.g. with only vite & vue)

**Comment by Tahul** [comment]
I'm fine with reducing output data, will be pushing that change.

I think we should at least preserve component name, and maybe the relative path inside the project (that might be useful when used in development, or to create some GitHub links from that data for example).

---

Data can already be queried via API with this version.

The only missing part is using the API in production, instead of inlining the chunk via an import.

Does it inlining the data via an import differs from loading it via an API query, as that chunk will be loaded anyways?

---

An important note from latest trials with this version;

- The HMR becomes very, very slow when using this version; the reason is this:
https://github.com/nuxtlabs/nuxt-component-meta/pull/43/files#diff-d38f71f7e31dc55444828b9c24a40d16b957e5851e84b3de1e85dfe8cb7ea12fR45-R64

What happens here is that I have to refresh the vue-component-meta checker on every request, as the file content changes and I don't know the method to refresh the content for a single file.

I checked `__internals__` from the vue-component-meta exposed instance, and couldn't find a method made to refresh the TS server files.

I tried running that in a parallel process, but that seem to break HMR.

Do you think you could point us to a fix for this issue @johnsoncodehk?

This PR is blocked by this issue, as it makes HMR really slow and all sizes of projects.

**Comment by johnsoncodehk** [comment]
@Tahul We need to have new API in vue-component-meta, maybe I can check it in next week, it would be nice if you could open a feature request.

**Comment by Tahul** [comment]
@johnsoncodehk ; https://github.com/johnsoncodehk/volar/issues/1889

You can find the feature request here, please let me know if anything else needed.

**Comment by Tahul** [comment]
Hey @johnsoncodehk ; I updated this PR, but it seems like the two new APIs `clearCache()` and `reload()` has no effect.

Using them before re-querying a component by its path won't change the result of the query.

That still blocks this PR, do you need a sandboxed reproduction?

**Comment by johnsoncodehk** [comment]
> That still blocks this PR, do you need a sandboxed reproduction?

Yes this will help, I'll also check if there are any issues with the reload logic before I have reproduction.

**Comment by johnsoncodehk** [comment]
I just found the reason when implement vue-component-meta playground, it should be fixed by https://github.com/johnsoncodehk/volar/commit/76d3ab8aa6debf7d5902e1f1eabd8eb27b5d2e15, please wait for v1.0.4.

**Comment by Tahul** [comment]
@Atinux ; done :)

It is ready for review @farnabaz ; @larbish ; @Atinux

**Comment by Tahul** [comment]
I added a feature, `transformers`.

You can push transformers via `nuxt.hook('component-meta:transformers', ({ transformers })  => { transformers.push() })`.

These are useful if you want to apply some transforms to components prior to parsing.

There is two ways to alter component parsing now:

- Pushing transformers via the hook
	- `(code, id) => string`
	- Has to be synchronous
- Using a Volar plugin, pushed into `tsconfig` relative to the project running `nuxt-component-meta`

An example is `<ContentSlot />` that won't be detected by vue-component-meta as a slot.

Via a transformer, we can rewrite `<ContentSlot :use="$slot.default" />` into `<slot #default />`, allowing `vue-component-meta` to detect it.

**Comment by Atinux** [comment]
Last step is to fix the CI and good for me to merge :rocket:

**Pull request merged**
