### PR TITLE
extract typescript props/emits metadata from AST

### PR DESCRIPTION
**Pull request by stafyniaksacha**
Extracting props from compiled sfc will always return base runtimes types because `defineProps` and `defineEmits` will be resolved into `defineComponent` props and emits options. [compileScript.ts#L1763-L1848](https://github.com/vuejs/core/blob/main/packages/compiler-sfc/src/compileScript.ts#L1763-L1848)

Also, we can note that compiler-sfc use babel parser internally and not typescript. 

The idea would be to walk through original typescript ASTs to retrieve as much information as the developer provided (we may have typed strings, typed objects/arrays, reuse other components props, ...)

A better way would be to create a program context instead of using ASTs, so typescript can resolve imports for us and resolve type for anything for us, more precisely that we can do with AST).  

This would require to use `vue-typescript` from volar which needs some tweaks before (see https://github.com/johnsoncodehk/volar/issues/1506)

### CODE REVIEW

**Comment by Atinux** [comment]
I let you review @farnabaz once you got some time :)

**Review by kevinmarrec — CHANGES_REQUESTED** [review]
Dunno what is exactly the state of this PR, but it will need testing suites :)

/cc @farnabaz How can we move this forward, could you review ?

**Comment by farnabaz** [comment]
We need to iterate on resolving non-primitive types. Importing external types, enums...

@stafyniaksacha Do you think this should wait for `vue-typescript`?

**Comment by stafyniaksacha** [comment]
> Do you think this should wait for vue-typescript?

Hum, I think not, we can not have any ETA for this, so it can be a good thing to start iterate without it.

**Comment by stafyniaksacha** [comment]
@Atinux @farnabaz I did some improvements I'm finally happy with props detection done in https://github.com/johnsoncodehk/volar/pull/1637

What do you think about the `schema` format?

**Comment by Atinux** [comment]
cc @kevinmarrec as well for the visual editor

**Comment by Atinux** [comment]
Also @Tahul

**Comment by Atinux** [comment]
So far I like the schema, seems a bit verbose but give nice informations :rocket:

**Comment by kevinmarrec** [comment]
I'm fine with any schema, we'll adapt our editor and could benefit of extra information :)

**Comment by stafyniaksacha** [comment]
There is still an issue when resolving inline type aliases (see: https://github.com/johnsoncodehk/volar/blob/master/packages/vue-component-meta/tests/index.spec.ts#L237-L251 / https://github.com/johnsoncodehk/volar/blob/master/packages/vue-component-meta/src/index.ts#L80)

So many things are objects, so it comes with a recursive nightmare.

Also, the defaults values are still not available

**Pull request closed without merging**
